name: Flake8 Format and Test

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  flake8-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: pip install flake8

      - name: Format code with Flake8
        run: |
          flake8 --max-line-length 120 --ignore=E203,W503,F405,F403,E402 --exclude=api/migrations/
